baseURL = "https://coopcycle.org/"
theme = "coopcycle"

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[blackfriday]
extensions = ["hardLineBreak"]

[Taxonomies]

[Languages]

### English

[Languages.en]
title = "CoopCycle"
description = "CoopCycle is a network of bike delivery co-ops."

### French

[Languages.fr]
title = "CoopCycle"
description = "CoopCycle est une fédération de coopératives de livraison à vélo."

### Spanish

[Languages.es]
title = "CoopCycle"
description = "CoopCycle es una federación de cooperativas de entrega por bicicleta."

[[Languages.fr.menu.main]]
name = "Blog"
weight = 4
identifier = "blog"
url = "https://blogs.mediapart.fr/coopcycle"

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
